### ISSUE TITLE
Can't build C-bindings

### ISSUE THREAD

**Issue by milen-prg** [malisipi/mui#21]
Windows 10 Pro 64bit

I installed V with TCC.
So I try to use mui c-bindings with command:

v -shared -cc tcc mui.v -o mui.dll

but it returns error:

builder error: 'commdlg.h' not found

**Comment by malisipi** [comment]
Did you install windows api header for TCC?

> If you not, you can follow [the *How to use TCC on Windows* instruction at FAQ](https://github.com/malisipi/mui#faq) to install

After installing, recompile with `v -shared -cc tcc -d no_backtrace mui.v -o mui.dll`

**Comment by milen-prg** [comment]
Apologize, now I add the folder winapi and the command:
 v -shared -cc tcc -d no_backtrace mui.v -o mui.dll
successfully made mui.dll

But, when I try the example, there was error:
 
C:\Users\mlap\Documents\Milen\Installs\Vlang\mui-main\c_bindings>gcc test.c mui.dll -o test.exe
In file included from test.c:1:0:
mui.h:1:2: warning: #warning "The API is unstable and a lot of thing will be changed in future. Please don't use in real-world application before stable-release." [-Wcpp]
 #warning "The API is unstable and a lot of thing will be changed in future. Please don't use in real-world application before stable-release."
  ^
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x1a): undefined reference to `mui_v_init'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x1f): undefined reference to `mui_get_null_object'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x6c): undefined reference to `mui_inputbox'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x89): undefined reference to `mui_messagebox'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x95): undefined reference to `mui_destroy'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x14d): undefined reference to `mui_parse_event_details'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x1ee): undefined reference to `mui_get_object_by_id'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x20a): undefined reference to `mui_change_object_property'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x253): undefined reference to `mui_create'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x271): undefined reference to `mui_button'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x28b): undefined reference to `mui_label'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x2a5): undefined reference to `mui_textbox'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x2bf): undefined reference to `mui_textarea'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x2d2): undefined reference to `mui_get_object_by_id'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x30c): undefined reference to `mui_scrollbar'
C:\Users\mlap\AppData\Local\Temp\cc81v63j.o:test.c:(.text+0x318): undefined reference to `mui_run'
collect2.exe: error: ld returned 1 exit status

And no .exe was generated.

P.S. Will consider to use GCC, but it is some problematic on Windows (MSYS2 is not usable in this case).

**Comment by milen-prg** [comment]
I reinstall all with GCC and all works fine.

**Comment by malisipi** [comment]
TCC has some problems about creating shared libraries. The executables uses the shared library that made by TCC can crash sometimes.
I'm glad to hear everything worked fine with GCC. If you have not another problem about the shared library, you can close the issue.
