### ISSUE TITLE
Suggesting Tray Menus

### ISSUE THREAD

**Issue by Wajinn** [malisipi/mui#23]
Would be an enhancement, if MUI could have a tray menu (also called system tray menu) option for desktops.  Note- could possibly be simplified as buttons inside a frame.  This is when a user right clicks the icon, there will be selectable options of what they can do.  In addition: 1) Setting for starting the main window from the icon or not (left click). 2) Have setting for tooltip or not (cursor on icon).

**Comment by malisipi** [comment]
It's really good idea. However in Linux, there are no unity for tray icons. So it could be hard to implement for Linux.

**Comment by malisipi** [comment]
Since we have a tray library for V, there are no requirement another tray library in V (if it's compatible with MUI). So i'm closing this issue with adding a reference this library to Readme file for see everyone who wants use tray library.
