### ISSUE TITLE
builder error: 'commdlg.h' not found

### ISSUE THREAD

**Issue by carpedil** [malisipi/mui#37]
v run .\examples\counter.v

```bash
> v doctor
V full version: V 0.4.2 37e5616.06fb8f0
OS: windows, Microsoft Windows 11 רҵ�� v22621 64-bit
Processor: 12 cpus, 64bit, little endian, 

getwd: C:\Users\cirya\.vmodules\mui
vexe: C:\Users\cirya\v\v.exe
vexe mtime: 2023-10-12 08:24:51

vroot: OK, value: C:\Users\cirya\v
VMODULES: OK, value: C:\Users\cirya\.vmodules
VTMP: OK, value: C:\Users\cirya\AppData\Local\Temp\v_0

Git version: git version 2.38.1.windows.1
Git vroot status: weekly.2023.30-498-g06fb8f0f
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,
operable program or batch file.

thirdparty/tcc status: thirdparty-windows-amd64 e90c2620
```

**Comment by malisipi** [comment]
It seems V is trying to use TCC by default.
Did you installed full windows api for TCC? It was explained in `How to use TCC on Windows` section of [FAQs](https://github.com/malisipi/mui?tab=readme-ov-file#faq).

Also you can install GCC (that compatible with V). You can found a guide about it in [V's github wiki](https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows#mingw).

If your issue isn't about it, please run `v -showcc -cc tcc ./examples/counter.v` and send the command output.

**Comment by malisipi** [comment]
I'm closing the issue due to inactivity and missing information. Re-open the issue, if encount with new problem.

**Comment by carpedil** [comment]
> It seems V is trying to use TCC by default. Did you installed full windows api for TCC? It was explained in `How to use TCC on Windows` section of [FAQs](https://github.com/malisipi/mui?tab=readme-ov-file#faq).
> 
> Also you can install GCC (that compatible with V). You can found a guide about it in [V's github wiki](https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows#mingw).
> 
> If your issue isn't about it, please run `v -showcc -cc tcc ./examples/counter.v` and send the command output.

ok, I'm sorry for the late reply, as I've been a bit busy with work lately
