### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by Wajinn** [malisipi/mui#4]
The link from the main page, https://github.com/malisipi/mui#documentation, points to a broken link (below).
https://github.com/malisipi/mui/blob/main/docs.md (broken link).

Maybe you want to post links to your new documentation, in place of the broken one:
https://github.com/malisipi/mui/blob/main/docs_md/mui.md
https://github.com/malisipi/mui/blob/main/docs_md/webview.md

**Comment by malisipi** [comment]
Thanks for your issue. I had totally forgotten to update documentation links.
