### ISSUE TITLE
Missing Features That Documentation Suggests Exists?

### ISSUE THREAD

**Issue by Wajinn** [malisipi/mui#5]
Missing features (?):

1. Documentation has fg (foreground color?), but doesn't appear to have been implemented yet.
 
	Text color (to be more obvious)/foreground color option needed

2. Text size (text_size, tSize) appears to not work or be implemented yet.

	This option could be very useful with button, label, checkbox, and also elsewhere.
 
3. On resize (onresize) of Window (like a setResizeEvent) option appears to be needed (which is not in documentation).
 
	Suggesting that an obvious onresize should exist, and ease of getting present width and height of a resized Window.

**Comment by malisipi** [comment]
1. That's exists already but mui haven't yet any function that change colors. You can look up [examples/colored_text.v](https://github.com/malisipi/mui/blob/main/examples/colored_text.v).

> Also, i you can set custom color scheme for your app. [examples/messagebox.v](https://github.com/malisipi/mui/blob/main/examples/messagebox.v#L14). All widgets use the color scheme. I recommend to use custom color scheme if you set color for widgets.

2. Text size is not implemented yet except labels. It will be available.

3. I'm not implemented onresize event. But it's simple to create. I will make it asap.

**Comment by Wajinn** [comment]
> 1. That's exists already but mui haven't yet any function that change colors. You can look up colored_text.v.

Yes, the labels are a very usable workaround, as can simply put and anchor over say a button.  Providing the example was excellent.
 
> 2. Text size is not implemented yet except labels. It will be available.

That would be great, as convenient and obvious to users.

> 3. I'm not implemented onresize event. But it's simple to create. I will make it asap.

Awesome.
