### ISSUE TITLE
Suggesting text size option for buttons, checkbox, menu bar text, etc...

### ISSUE THREAD

**Issue by Wajinn** [malisipi/mui#9]
> Text size (text_size, tSize) appears to not work or be implemented yet. This option could be very useful with button, label, checkbox, and also elsewhere.
> 
> Text size is not implemented yet except labels. It will be available.

Creating a separate issue for text size, so that it will not be lost. Labels can be used as a kind of workaround, because they implement size, but can be problematic. For example, users having to put a label over a checkbox, to get the text size feature is not convenient.

Link to related- https://github.com/malisipi/mui/issues/5

**Comment by malisipi** [comment]
I added text_size support for button, checkbox, passwordbox, radio, switch and textbox. I will implement for menubar and other widgets (like progress) asap.

**Comment by Wajinn** [comment]
> I will implement for menubar and other widgets (like progress) asap.

Looking great so far.  Will keep open until progress bar text finished.  Appears to need modification too, because progress bar text not matching other sizes can look odd or if the progress bar is too narrow then the text can look too big.
